all:
  vars:
    cartridge_app_name: vezdekod
    cartridge_package_path: ./vezdekod-0.1.0-1-gb02b3c6.deb
    cartridge_cluster_cookie: secret-cookie
    # ansible_python_interpreter: /usr/bin/python2
    # may be useful for vagrant
    # ansible_ssh_private_key_file: ~/.vagrant.d/insecure_private_key
    # ansible_ssh_common_args: '-o IdentitiesOnly=yes -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'

  hosts:
    vezdekod.router:
      config:
        advertise_uri: localhost:3301
        http_port: 8081

    vezdekod.s1-master:
      config:
        advertise_uri: localhost:3302
        http_port: 8082

    vezdekod.s1-replica:
      config:
        advertise_uri: localhost:3303
        http_port: 8083

    vezdekod.s2-master:
      config:
        advertise_uri: localhost:3304
        http_port: 8084

    vezdekod.s2-replica:
      config:
        advertise_uri: localhost:3305
        http_port: 8085

    # vezdekod-stateboard:
    #   config:
    #     listen: localhost:4401
    #     password: passwd

  children:
    # group instances by machines
    machine_1:
      vars:
        # first machine address and connection opts
        ansible_host: tarantool.leadpogrommer.ru
        ansible_user: ubuntu

      hosts:  # instances to be started on this machine
        vezdekod.router:
        vezdekod.s1-replica:
        vezdekod.s1-master:
        vezdekod.s2-master:
        vezdekod.s2-replica:
        # vezdekod-stateboard:

    # group instances by replicasets
    api_replicaset:  # replicaset storage-1
      hosts:  # instances
        vezdekod.router:
      vars:
        # replicaset configuration
        replicaset_alias: api-rs
        roles:
          - 'api'
        # failover_priority:
        #   - storage-1
        #   - storage-1-replica
    storage_replicaset:  # replicaset storage-1
      hosts:  # instances
        vezdekod.s1-master:
      vars:
        # replicaset configuration
        replicaset_alias: storage-rs
        roles:
          - 'storage'
        # failover_priority:
        #   - storage-1
        #   - storage-1-replica